language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sdl2
  - sudo apt-get install -y sdl2_image
