language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libsdl2-dev
  - sudo apt-get install libsdl2_image-dev
