[package]
name = "toffee"
version = "0.2.0"
authors = ["Johan Sjölin <johan.sjolin@gmail.com>"]

[dependencies]
image = "0.23.12"
winit = "0.24"
shaderc = "0.7"
cgmath = "0.17"
env_logger = "0.8.2"
log = "0.4.11"
wgpu = "0.6.2"
futures = "0.3.8"
